/*
Ncdaf_EventExposure

CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.2.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdaf

import (
	"encoding/json"
)

// CdafEventSubscriptionInfo Individual CDAF Event Subscription Information
type CdafEventSubscriptionInfo struct {
	// String providing an URI formatted according to RFC 3986.
	SubId string `json:"subId"`
	// String providing an URI formatted according to RFC 3986.
	OldSubId *string `json:"oldSubId,omitempty"`
}

// NewCdafEventSubscriptionInfo instantiates a new CdafEventSubscriptionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdafEventSubscriptionInfo(subId string) *CdafEventSubscriptionInfo {
	this := CdafEventSubscriptionInfo{}
	this.SubId = subId
	return &this
}

// NewCdafEventSubscriptionInfoWithDefaults instantiates a new CdafEventSubscriptionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdafEventSubscriptionInfoWithDefaults() *CdafEventSubscriptionInfo {
	this := CdafEventSubscriptionInfo{}
	return &this
}

// GetSubId returns the SubId field value
func (o *CdafEventSubscriptionInfo) GetSubId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubId
}

// GetSubIdOk returns a tuple with the SubId field value
// and a boolean to check if the value has been set.
func (o *CdafEventSubscriptionInfo) GetSubIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubId, true
}

// SetSubId sets field value
func (o *CdafEventSubscriptionInfo) SetSubId(v string) {
	o.SubId = v
}

// GetOldSubId returns the OldSubId field value if set, zero value otherwise.
func (o *CdafEventSubscriptionInfo) GetOldSubId() string {
	if o == nil || o.OldSubId == nil {
		var ret string
		return ret
	}
	return *o.OldSubId
}

// GetOldSubIdOk returns a tuple with the OldSubId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdafEventSubscriptionInfo) GetOldSubIdOk() (*string, bool) {
	if o == nil || o.OldSubId == nil {
		return nil, false
	}
	return o.OldSubId, true
}

// HasOldSubId returns a boolean if a field has been set.
func (o *CdafEventSubscriptionInfo) HasOldSubId() bool {
	if o != nil && o.OldSubId != nil {
		return true
	}

	return false
}

// SetOldSubId gets a reference to the given string and assigns it to the OldSubId field.
func (o *CdafEventSubscriptionInfo) SetOldSubId(v string) {
	o.OldSubId = &v
}

func (o CdafEventSubscriptionInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["subId"] = o.SubId
	}
	if o.OldSubId != nil {
		toSerialize["oldSubId"] = o.OldSubId
	}
	return json.Marshal(toSerialize)
}

type NullableCdafEventSubscriptionInfo struct {
	value *CdafEventSubscriptionInfo
	isSet bool
}

func (v NullableCdafEventSubscriptionInfo) Get() *CdafEventSubscriptionInfo {
	return v.value
}

func (v *NullableCdafEventSubscriptionInfo) Set(val *CdafEventSubscriptionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCdafEventSubscriptionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCdafEventSubscriptionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdafEventSubscriptionInfo(val *CdafEventSubscriptionInfo) *NullableCdafEventSubscriptionInfo {
	return &NullableCdafEventSubscriptionInfo{value: val, isSet: true}
}

func (v NullableCdafEventSubscriptionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdafEventSubscriptionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


