/*
Ncdaf_EventExposure

CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.2.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CdafEventType Describes the supported event types of Ncadf_EventExposure Service
type CdafEventType struct {
	CdafEventTypeAnyOf *CdafEventTypeAnyOf
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *CdafEventType) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into CdafEventTypeAnyOf
	err = json.Unmarshal(data, &dst.CdafEventTypeAnyOf);
	if err == nil {
		jsonCdafEventTypeAnyOf, _ := json.Marshal(dst.CdafEventTypeAnyOf)
		if string(jsonCdafEventTypeAnyOf) == "{}" { // empty struct
			dst.CdafEventTypeAnyOf = nil
		} else {
			return nil // data stored in dst.CdafEventTypeAnyOf, return on the first match
		}
	} else {
		dst.CdafEventTypeAnyOf = nil
	}

	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("Data failed to match schemas in anyOf(CdafEventType)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *CdafEventType) MarshalJSON() ([]byte, error) {
	if src.CdafEventTypeAnyOf != nil {
		return json.Marshal(&src.CdafEventTypeAnyOf)
	}

	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableCdafEventType struct {
	value *CdafEventType
	isSet bool
}

func (v NullableCdafEventType) Get() *CdafEventType {
	return v.value
}

func (v *NullableCdafEventType) Set(val *CdafEventType) {
	v.value = val
	v.isSet = true
}

func (v NullableCdafEventType) IsSet() bool {
	return v.isSet
}

func (v *NullableCdafEventType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdafEventType(val *CdafEventType) *NullableCdafEventType {
	return &NullableCdafEventType{value: val, isSet: true}
}

func (v NullableCdafEventType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdafEventType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


